"""
Prometheus metrics for sa-fraud-shield.

Exposes the following metrics at /metrics:

Counters:
    fraud_shield_decisions_total{decision, payment_rail}   — APPROVE/STEP_UP/BLOCK counts
    fraud_shield_alerts_total{severity, fraud_type}        — FraudAlert counts by severity

Histograms:
    fraud_shield_ensemble_score                            — score distribution (buckets 0.1 steps)
    fraud_shield_sim_swap_score                            — SIM swap model score distribution
    fraud_shield_scoring_latency_ms                        — end-to-end scoring latency

Gauges:
    fraud_shield_psi_score{feature}                        — PSI drift score per feature
    fraud_shield_model_loaded{model}                       — 1 if model loaded, 0 otherwise
"""

from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram

# ── Decision counters ─────────────────────────────────────────────────────────
DECISIONS = Counter(
    "fraud_shield_decisions_total",
    "Fraud scoring decisions by outcome and payment rail",
    ["decision", "payment_rail"],
)

ALERTS = Counter(
    "fraud_shield_alerts_total",
    "FraudAlerts generated by severity and predicted fraud type",
    ["severity", "fraud_type"],
)

# ── Score distributions ───────────────────────────────────────────────────────
ENSEMBLE_SCORE = Histogram(
    "fraud_shield_ensemble_score",
    "Ensemble fraud score distribution",
    buckets=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
)

SIM_SWAP_SCORE = Histogram(
    "fraud_shield_sim_swap_score",
    "SIM swap model score distribution",
    buckets=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
)

# ── Latency ───────────────────────────────────────────────────────────────────
SCORING_LATENCY = Histogram(
    "fraud_shield_scoring_latency_ms",
    "End-to-end scoring latency in milliseconds",
    buckets=[1, 5, 10, 25, 50, 100, 250, 500, 1000],
)

# ── Drift gauges ──────────────────────────────────────────────────────────────
PSI_SCORE = Gauge(
    "fraud_shield_psi_score",
    "Population Stability Index drift score per feature (>0.2 = significant drift)",
    ["feature"],
)

# ── Model health ──────────────────────────────────────────────────────────────
MODEL_LOADED = Gauge(
    "fraud_shield_model_loaded",
    "Whether each model is currently loaded (1=loaded, 0=not loaded)",
    ["model"],
)


def record_score_result(result) -> None:
    """Record all metrics for a ScoreResult. Called from scorer after each transaction."""
    rail = "unknown"
    decision = result.decision or "APPROVE"

    DECISIONS.labels(decision=decision, payment_rail=rail).inc()
    ENSEMBLE_SCORE.observe(result.ensemble_score)
    SCORING_LATENCY.observe(result.latency_ms)

    if result.sim_swap_score is not None:
        SIM_SWAP_SCORE.observe(result.sim_swap_score)

    if result.alert is not None:
        severity = (
            result.alert.severity.value
            if hasattr(result.alert.severity, "value")
            else str(result.alert.severity)
        )
        fraud_type = (
            result.alert.predicted_fraud_type.value
            if result.alert.predicted_fraud_type
            and hasattr(result.alert.predicted_fraud_type, "value")
            else "unknown"
        )
        ALERTS.labels(severity=severity, fraud_type=fraud_type).inc()


def record_score_result_with_rail(result, payment_rail: str) -> None:
    """Record metrics with payment rail label."""
    decision = result.decision or "APPROVE"

    DECISIONS.labels(decision=decision, payment_rail=payment_rail).inc()
    ENSEMBLE_SCORE.observe(result.ensemble_score)
    SCORING_LATENCY.observe(result.latency_ms)

    if result.sim_swap_score is not None:
        SIM_SWAP_SCORE.observe(result.sim_swap_score)

    if result.alert is not None:
        severity = (
            result.alert.severity.value
            if hasattr(result.alert.severity, "value")
            else str(result.alert.severity)
        )
        fraud_type = (
            result.alert.predicted_fraud_type.value
            if result.alert.predicted_fraud_type
            and hasattr(result.alert.predicted_fraud_type, "value")
            else "unknown"
        )
        ALERTS.labels(severity=severity, fraud_type=fraud_type).inc()
