"""
Unit tests for shared/schemas.py Pydantic data contracts.

Validates:
  - Transaction construction, field coercion, and cross-field validation
  - Account phone validation
  - FraudAlert severity mapping
  - ScoreResponse decision values
  - KafkaTransactionEvent envelope
"""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal

import pytest
from pydantic import ValidationError

from shared.constants import FraudType, PaymentRail, SABank, SAProvince
from shared.schemas import (
    Account,
    AccountFeatures,
    AlertSeverity,
    FraudAlert,
    KafkaTransactionEvent,
    ScoreResponse,
    Transaction,
)

# ── Transaction ───────────────────────────────────────────────────────────────


class TestTransaction:
    def _base(self, **overrides) -> dict:
        base = {
            "transaction_id": "tx-001",
            "timestamp": datetime(2026, 3, 15, 10, 0, 0, tzinfo=UTC),
            "sender_account_id": "acc-001",
            "amount_zar": Decimal("500.00"),
            "payment_rail": PaymentRail.PAYSHAP,
        }
        base.update(overrides)
        return base

    def test_valid_transaction(self):
        tx = Transaction(**self._base())
        assert tx.amount_zar == Decimal("500.00")
        assert tx.payment_rail == PaymentRail.PAYSHAP

    def test_amount_coerced_from_float(self):
        tx = Transaction(**self._base(amount_zar=1500.5))
        assert tx.amount_zar == Decimal("1500.5")

    def test_amount_coerced_from_string(self):
        tx = Transaction(**self._base(amount_zar="2000.00"))
        assert tx.amount_zar == Decimal("2000.00")

    def test_zero_amount_rejected(self):
        with pytest.raises(ValidationError):
            Transaction(**self._base(amount_zar=Decimal("0")))

    def test_negative_amount_rejected(self):
        with pytest.raises(ValidationError):
            Transaction(**self._base(amount_zar=Decimal("-100")))

    def test_fraud_type_without_is_fraud_raises(self):
        with pytest.raises(ValidationError, match="fraud_type set but is_fraud=False"):
            Transaction(
                **self._base(
                    is_fraud=False,
                    fraud_type=FraudType.SIM_SWAP,
                )
            )

    def test_fraud_type_with_is_fraud_true_ok(self):
        tx = Transaction(**self._base(is_fraud=True, fraud_type=FraudType.SIM_SWAP))
        assert tx.fraud_type == FraudType.SIM_SWAP

    def test_no_fraud_type_with_is_fraud_false_ok(self):
        tx = Transaction(**self._base(is_fraud=False))
        assert tx.is_fraud is False

    def test_defaults(self):
        tx = Transaction(**self._base())
        assert tx.sim_swap_detected is False
        assert tx.loadshedding_active is False
        assert tx.loadshedding_stage is None
        assert tx.is_fraud is None

    def test_transaction_id_autogenerated_when_omitted(self):
        data = self._base()
        data.pop("transaction_id")
        tx = Transaction(**data)
        assert len(tx.transaction_id) > 0


# ── Account ───────────────────────────────────────────────────────────────────


class TestAccount:
    def _base(self, **overrides) -> dict:
        base = {
            "bank": SABank.CAPITEC,
            "account_number": "1234567890",
            "registration_phone": "+27831234567",
            "province": SAProvince.GAUTENG,
            "account_age_days": 365,
        }
        base.update(overrides)
        return base

    def test_valid_account(self):
        acc = Account(**self._base())
        assert acc.bank == SABank.CAPITEC

    def test_invalid_phone_rejected(self):
        with pytest.raises(ValidationError):
            Account(**self._base(registration_phone="0831234567"))  # not E.164

    def test_negative_account_age_rejected(self):
        with pytest.raises(ValidationError):
            Account(**self._base(account_age_days=-1))

    def test_zero_age_allowed(self):
        acc = Account(**self._base(account_age_days=0))
        assert acc.account_age_days == 0

    def test_account_id_autogenerated(self):
        acc = Account(**self._base())
        assert len(acc.account_id) > 0


# ── FraudAlert ────────────────────────────────────────────────────────────────


class TestFraudAlert:
    def test_valid_alert(self):
        alert = FraudAlert(
            transaction_id="tx-001",
            account_id="acc-001",
            timestamp=datetime(2026, 3, 15, 10, 0, 0, tzinfo=UTC),
            severity=AlertSeverity.HIGH,
            ensemble_score=0.85,
        )
        assert alert.status == "OPEN"
        assert alert.severity == AlertSeverity.HIGH

    def test_score_out_of_range_rejected(self):
        with pytest.raises(ValidationError):
            FraudAlert(
                transaction_id="tx-001",
                account_id="acc-001",
                timestamp=datetime.now(UTC),
                severity=AlertSeverity.CRITICAL,
                ensemble_score=1.5,  # > 1.0
            )

    def test_score_zero_allowed(self):
        alert = FraudAlert(
            transaction_id="tx-001",
            account_id="acc-001",
            timestamp=datetime.now(UTC),
            severity=AlertSeverity.LOW,
            ensemble_score=0.0,
        )
        assert alert.ensemble_score == 0.0

    def test_alert_id_autogenerated(self):
        alert = FraudAlert(
            transaction_id="tx-001",
            account_id="acc-001",
            timestamp=datetime.now(UTC),
            severity=AlertSeverity.MEDIUM,
            ensemble_score=0.5,
        )
        assert len(alert.alert_id) > 0


# ── ScoreResponse ─────────────────────────────────────────────────────────────


class TestScoreResponse:
    def test_approve_response(self):
        resp = ScoreResponse(
            transaction_id="tx-001",
            ensemble_score=0.1,
            decision="APPROVE",
        )
        assert resp.decision == "APPROVE"
        assert resp.alert is None

    def test_block_response_with_alert(self):
        alert = FraudAlert(
            transaction_id="tx-001",
            account_id="acc-001",
            timestamp=datetime.now(UTC),
            severity=AlertSeverity.CRITICAL,
            ensemble_score=0.95,
        )
        resp = ScoreResponse(
            transaction_id="tx-001",
            ensemble_score=0.95,
            decision="BLOCK",
            alert=alert,
        )
        assert resp.decision == "BLOCK"
        assert resp.alert is not None

    def test_score_bounds_enforced(self):
        with pytest.raises(ValidationError):
            ScoreResponse(
                transaction_id="tx-001",
                ensemble_score=1.1,
                decision="BLOCK",
            )


# ── AccountFeatures ───────────────────────────────────────────────────────────


class TestAccountFeatures:
    def test_zero_defaults(self):
        af = AccountFeatures(
            account_id="acc-001",
            computed_at=datetime.now(UTC),
        )
        assert af.tx_count_5min == 0
        assert af.sim_swap_detected is False
        assert af.amount_sum_24hr == Decimal("0")

    def test_full_features(self):
        af = AccountFeatures(
            account_id="acc-001",
            computed_at=datetime.now(UTC),
            tx_count_5min=3,
            tx_count_1hr=12,
            sim_swap_detected=True,
            device_change_24h=True,
        )
        assert af.tx_count_5min == 3
        assert af.sim_swap_detected is True


# ── KafkaTransactionEvent ─────────────────────────────────────────────────────


class TestKafkaTransactionEvent:
    def test_envelope_wraps_transaction(self):
        tx = Transaction(
            timestamp=datetime.now(UTC),
            sender_account_id="acc-001",
            amount_zar=Decimal("500"),
            payment_rail=PaymentRail.EFT,
        )
        event = KafkaTransactionEvent(
            produced_at=datetime.now(UTC),
            partition_key=tx.sender_account_id,
            payload=tx,
        )
        assert event.event_type == "transaction.created"
        assert event.schema_version == "1.0"
        assert event.payload.sender_account_id == "acc-001"

    def test_event_id_autogenerated(self):
        tx = Transaction(
            timestamp=datetime.now(UTC),
            sender_account_id="acc-001",
            amount_zar=Decimal("100"),
            payment_rail=PaymentRail.MOBILE_APP,
        )
        event = KafkaTransactionEvent(
            produced_at=datetime.now(UTC),
            partition_key="acc-001",
            payload=tx,
        )
        assert len(event.event_id) > 0
